[tools]
flutter = "3.38.5-stable"

# mise run check

[tasks.check]
description = "Flutter のバージョン更新"
run = "mise ls-remote flutter"

[tasks.mise-update]
description = "mise自体 の更新"
run = "brew upgrade mise"
