name: socket_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  chewie: ^1.13.0
  country_list_pick: ^1.0.1+1
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_slidable: ^4.0.3
  flutter_spinkit: ^5.2.2
  get: ^4.7.3
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: any
  mime: ^2.0.0
  emoji_picker_flutter: ^4.4.0
  shared_preferences: ^2.5.4
  sizer: ^2.0.15
  socket_io_client: ^3.1.4
  stream_transform: ^2.1.1
  video_compress: ^3.1.4
  video_player: ^2.10.1
  device_info_plus: ^12.3.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^6.0.0
  flutter_app_badger: ^1.5.0
  flip_card: ^0.7.0
  # device_preview: ^1.1.0
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.7.2
  uuid: ^4.5.2
  skeletonizer: ^2.1.2
  pin_code_fields: ^8.0.1

  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.1
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  visibility_detector: ^0.4.0+2
  flutter_markdown: ^0.7.7
  gal: ^2.3.2
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/lotties/
    - assets/markdown/
    - .env

flutter_icons:
  image_path: 'assets/icon/icon-ios.png'
  image_path_ios: 'assets/icon/icon-ios.png'
  android: true
  ios: true
  adaptive_icon_foreground: 'assets/icon/icon-android.png'
  adaptive_icon_background: '#DCE6E7'

flutter_native_splash:
  image: 'assets/icon/splash-icon.png'
  color: '#DCE6E7'
  fullscreen: true
  android_12:
    icon_background_color: '#DCE6E7'
    image: 'assets/icon/splash-icon.png'
